export const productList = [
  {
    id: 1,
    itemName: "ট্রিট চকো ললিপপ",
    label: "ট্রিট চকো ললিপপ",
    basePrice: 240,
  },
  {
    id: 2,
    itemName: "চকো ললিপপ চেইন",
    label: "চকো ললিপপ চেইন",
    basePrice: 240,
  },
  { id: 3, itemName: "হুইসেল ললিপপ", label: "হুইসেল ললিপপ", basePrice: 290 },
  { id: 4, itemName: "ট্রিট ললিপপ", label: "ট্রিট ললিপপ", basePrice: 350 },
  {
    id: 5,
    itemName: "স্ট্যান্ড ললিপপ",
    label: "স্ট্যান্ড ললিপপ",
    basePrice: 370,
  },
  { id: 6, itemName: "আমরস ললিপপ", label: "আমরস ললিপপ", basePrice: 240 },
  { id: 7, itemName: "চাওচাও জগ ললি", label: "চাওচাও জগ ললি", basePrice: 320 },
  { id: 8, itemName: "চাওচাও ওয়ারলি", label: "চাওচাও ওয়ারলি", basePrice: 180 },
  { id: 9, itemName: "ফুটবল ললিপপ", label: "ফুটবল ললিপপ", basePrice: 290 },
  {
    id: 10,
    itemName: "জুসি মেগা ললিপপ",
    label: "জুসি মেগা ললিপপ",
    basePrice: 75,
  },
  { id: 11, itemName: "মিল্কিস্টিক", label: "মিল্কিস্টিক", basePrice: 160 },
  {
    id: 12,
    itemName: "মিল্কিস্টিক কিং",
    label: "মিল্কিস্টিক কিং",
    basePrice: 370,
  },
  { id: 13, itemName: "ফুটফিল বক্স", label: "ফুটফিল বক্স", basePrice: 75 },
  { id: 14, itemName: "ফুটফিল জার", label: "ফুটফিল জার", basePrice: 300 },
  { id: 15, itemName: "বাবলগাম", label: "বাবলগাম", basePrice: 165 },
  { id: 16, itemName: "ফুটবলগাম", label: "ফুটবলগাম", basePrice: 190 },
  {
    id: 17,
    itemName: "হুররে কিং মামা",
    label: "হুররে কিং মামা",
    basePrice: 140,
  },
  {
    id: 18,
    itemName: "হুররে চেইন মামা",
    label: "হুররে চেইন মামা",
    basePrice: 270,
  },
  {
    id: 19,
    itemName: "ডাবল লেয়ার মামা",
    label: "ডাবল লেয়ার মামা",
    basePrice: 140,
  },
  {
    id: 20,
    itemName: "প্রিমিও ওয়েফার",
    label: "প্রিমিও ওয়েফার",
    basePrice: 120,
  },
  {
    id: 21,
    itemName: "হুররে মেগা স্টবেরি",
    label: "হুররে মেগা স্টবেরি",
    basePrice: 120,
  },
  { id: 22, itemName: "বাড্ডি ওয়েফার", label: "বাড্ডি ওয়েফার", basePrice: 160 },
  {
    id: 23,
    itemName: "ডেইরি মিল্ক ৫ টাকা",
    label: "ডেইরি মিল্ক ৫ টাকা",
    basePrice: 95,
  },
  {
    id: 24,
    itemName: "ডেইরি মিল্ক ১০ টাকা",
    label: "ডেইরি মিল্ক ১০ টাকা",
    basePrice: 210,
  },
  {
    id: 25,
    itemName: "ডিজার্ট ৫ টাকা",
    label: "ডিজার্ট ৫ টাকা",
    basePrice: 40,
  },
  {
    id: 26,
    itemName: "ডিজার্ট ১০ টাকা",
    label: "ডিজার্ট ১০ টাকা",
    basePrice: 155,
  },
  {
    id: 27,
    itemName: "প্রিমিও চকোলেট",
    label: "প্রিমিও চকোলেট",
    basePrice: 305,
  },
  { id: 28, itemName: "কোকোনাট বার", label: "কোকোনাট বার", basePrice: 145 },
  {
    id: 29,
    itemName: "স্টবেরি কোকোনাট বার",
    label: "স্টবেরি কোকোনাট বার",
    basePrice: 145,
  },
  { id: 30, itemName: "চকোবাটন", label: "চকোবাটন", basePrice: 190 },
  { id: 31, itemName: "সানি একলেয়ার", label: "সানি একলেয়ার", basePrice: 250 },
  {
    id: 32,
    itemName: "ট্রিট ম্যাজিক বক্স",
    label: "ট্রিট ম্যাজিক বক্স",
    basePrice: 280,
  },
  { id: 33, itemName: "সানি লাভ বক্স", label: "সানি লাভ বক্স", basePrice: 130 },
  {
    id: 34,
    itemName: "একলেয়ার গিফট বক্স",
    label: "একলেয়ার গিফট বক্স",
    basePrice: 95,
  },
  {
    id: 35,
    itemName: "স্কয়ার গিফট বক্স",
    label: "স্কয়ার গিফট বক্স",
    basePrice: 100,
  },
  { id: 36, itemName: "রাউন্ড বক্স", label: "রাউন্ড বক্স", basePrice: 70 },
  {
    id: 37,
    itemName: "প্রিমিও প্যারাডাইজ",
    label: "প্রিমিও প্যারাডাইজ",
    basePrice: 380,
  },
  { id: 38, itemName: "হ্যাপিকাপ রেড", label: "হ্যাপিকাপ রেড", basePrice: 225 },
  { id: 39, itemName: "আইলাভ এরাবিন", label: "আইলাভ এরাবিন", basePrice: 265 },
  {
    id: 40,
    itemName: "প্লটো ব্লিস্টার ঘড়ি",
    label: "প্লটো ব্লিস্টার ঘড়ি",
    basePrice: 280,
  },
  { id: 41, itemName: "প্রান হাজমোলা", label: "প্রান হাজমোলা", basePrice: 255 },
  { id: 42, itemName: "সফট চিউ কাপ", label: "সফট চিউ কাপ", basePrice: 160 },
  { id: 43, itemName: "জেলিবিন চেইন", label: "জেলিবিন চেইন", basePrice: 95 },
  { id: 44, itemName: "চকোবল চেইন", label: "চকোবল চেইন", basePrice: 95 },
  {
    id: 45,
    itemName: "মিল্ক ম্যাংগো চেইন",
    label: "মিল্ক ম্যাংগো চেইন",
    basePrice: 95,
  },
  { id: 46, itemName: "বোল", label: "বোল", basePrice: 30 },
  { id: 47, itemName: "বালতি", label: "বালতি", basePrice: 30 },
  { id: 1, itemName: "পালস ম্যাংগো", label: "পালস ম্যাংগো", basePrice: 300 },
  { id: 2, itemName: "পালস তেতুল", label: "পালস তেতুল", basePrice: 300 },
  { id: 3, itemName: "ব্রো লাভ বক্স", label: "ব্রো লাভ বক্স", basePrice: 115 },
  {
    id: 4,
    itemName: "ম্যাংগো বার বক্স",
    label: "ম্যাংগো বার বক্স",
    basePrice: 100,
  },
  {
    id: 5,
    itemName: "ম্যাংগো বার জার",
    label: "ম্যাংগো বার জার",
    basePrice: 205,
  },
  { id: 6, itemName: "মাহা ক্যান্ডি", label: "মাহা ক্যান্ডি", basePrice: 300 },
  { id: 7, itemName: "ফ্রুটো চকলেট", label: "ফ্রুটো চকলেট", basePrice: 290 },
  { id: 8, itemName: "গ্লুকোজ ডি", label: "গ্লুকোজ ডি", basePrice: 65 },
  { id: 9, itemName: "প্লুটো চামচ", label: "প্লুটো চামচ", basePrice: 300 },
  { id: 10, itemName: "রুটি", label: "রুটি", basePrice: 280 },
  { id: 11, itemName: "ভেগান কেক", label: "ভেগান কেক", basePrice: 285 },
  { id: 12, itemName: "ছিতিয়ান কেক", label: "ছিতিয়ান কেক", basePrice: 280 },
];
